# Generated by Django 5.1.5 on 2025-01-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
