# Generated by Django 5.1.5 on 2025-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('department', models.CharField(max_length=255)),
                ('resources', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
